### ISSUE TITLE
NPM publish permission

### ISSUE THREAD

**Issue by dekelev** [fixate/feathers-stripe-webhooks#2]
Hi @sdbondi 

I've merged v2.1.0 to master and cannot publish to NPM as I'm missing that permission.

Here are the list of changes included in this version:

- Updated dependencies
- Upgraded Babel modules & settings
- Changed babel build target to be NodeJS 8
- Added `engines` section to package.json with NodeJS 8 and above
- Replaced deprecated sinon's reset method with resetHistory method
- Added package-lock.json file
- Added `.idea` dir to the gitignore file

**Comment by larrybotha** [comment]
@dekelev Thanks! I've added you as an admin on the repo - let me know if you're unable to publish to npm.

**Comment by dekelev** [comment]
Thanks @larrybotha, but for NPM publish permissions, you'll need to add me as maintainer here: https://www.npmjs.com/package/feathers-stripe-webhooks/access

**Comment by larrybotha** [comment]
Thanks @dekelev - I had to hunt down the credentials for the company NPM account O.o

You're now a maintainer in NPM.

**Comment by dekelev** [comment]
Still doesn't work. I can see it my list of packages, but still can't publish. did you set it with write permission?

**Comment by larrybotha** [comment]
@dekelev yup I did - but perhaps it's refusing to publish because I published.

Are you getting a 401 or 403 on publish?

**Comment by dekelev** [comment]
403 error `You do not have permission to publish "feathers-stripe-webhooks". Are you logged in as the correct user? : feathers-stripe-webhooks`

**Comment by dekelev** [comment]
seems like it worked. published 2.1.0, just caching issue maybe. thanks!

**Comment by larrybotha** [comment]
Ye that's weird - you should have gotten `403 Forbidden - PUT https://registry.npmjs.org/feathers-stripe-webhooks - You cannot publish over the previously published versions: 2.1.0` instead.

Seems all good now - thanks!

**Comment by dekelev** [comment]
Eventually that was the error, that I can't republished the same version
again.

בתאריך יום ד׳, 8 בינו׳ 2020, 0:29, מאת Larry Botha ‏<
notifications@github.com>:
